### ISSUE TITLE
Mobile Responsive: Auto align Images

### ISSUE THREAD

**Issue by rorar** [projectestac/wordpress-tinymce-advanced#6]
By default TMCE-A adds height and width attributes.
For mobile responsiveness its bad :-/
Would be great to get that fixed by default :-)

For a workaround See here:
https://stackoverflow.com/questions/28631932/responsive-image-tinymce-image-link
But images gets squashed...

**Comment by toniginard** [comment]
We're not the maintainers of this plugin. We just do a customization for our applications. Please report it to its developers:
[https://wordpress.org/plugins/tinymce-advanced/](https://wordpress.org/plugins/tinymce-advanced/)

Best wishes
